In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset=pd.read_csv("insurance_pre.csv")

In [4]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [7]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [8]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [9]:
dependent=dataset[['charges']]

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['mse','mae','friedman_mse'],'max_features': ['auto','sqrt','log2'],'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(x_train,y_train)

C:\Users\WELCOME\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

Fitting 3 folds for each of 18 candidates, totalling 54 fits

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    4.7s
[Parallel(n_jobs=-1)]: Done  47 out of  54 | elapsed:    4.9s remaining:    0.6s
[Parallel(n_jobs=-1)]: Done  54 out of  54 | elapsed:    4.9s finished

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=DecisionTreeRegressor(criterion='mse', max_depth=None,
                                             max_features=None,
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             presort=False, random_state=None,
                                             splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [13]:
re=grid.cv_results_
print('The R_score value for best parameter{}:'.format(grid.best_params_))

The R_score value for best parameter{'criterion': 'mae', 'max_features': 'auto', 'splitter': 'random'}:

In [14]:
table=pd.DataFrame.from_dict(re)

In [15]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.015625,1.348699e-06,0.010417,7.366033e-03,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",0.575614,0.700063,0.640089,0.638589,0.050817,4
1,0.005209,7.366820e-03,0.005207,7.364347e-03,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",0.611669,0.687212,0.716329,0.671737,0.044106,2
2,0.006261,2.527357e-03,0.004996,8.167294e-04,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.485819,0.621369,0.665983,0.591057,0.076611,15
3,0.005330,4.714831e-04,0.004331,1.245663e-03,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.574569,0.615398,0.720995,0.636987,0.061697,5
4,0.009660,4.107107e-03,0.004664,4.701903e-04,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",0.644417,0.647773,0.504477,0.598889,0.066774,12
5,0.006663,2.493514e-03,0.005330,1.884751e-03,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",0.496563,0.618158,0.562876,0.559199,0.049709,17
6,0.094318,4.918721e-03,0.004665,1.247299e-03,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",0.608300,0.630822,0.665560,0.634894,0.023553,6
7,0.045874,2.186501e-02,0.004665,4.709214e-04,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",0.668125,0.690574,0.707249,0.688649,0.016030,1
8,0.020653,3.088780e-03,0.003999,8.161455e-04,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.513179,0.681503,0.660049,0.618243,0.074806,9
9,0.016057,3.180363e-03,0.002399,1.766160e-03,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.688928,0.609932,0.539783,0.612881,0.060924,10
10,0.021641,8.506695e-03,0.007280,7.062903e-03,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",0.593938,0.585669,0.701926,0.627178,0.052963,8
11,0.021937,6.096717e-03,0.003665,4.706964e-04,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",0.500995,0.665412,0.614200,0.593536,0.068695,14
12,0.005995,2.247832e-07,0.003665,4.714829e-04,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.554906,0.713137,0.648997,0.639013,0.064982,3
13,0.006663,9.426284e-04,0.004997,8.162427e-04,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.412091,0.673114,0.704880,0.596695,0.131177,13
14,0.005330,1.247596e-03,0.002999,5.947204e-07,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.609996,0.696671,0.577630,0.628099,0.050256,7
15,0.004663,4.699655e-04,0.004331,1.247681e-03,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.536576,0.611850,0.649746,0.599391,0.047034,11
16,0.004330,4.715394e-04,0.003332,9.429093e-04,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.496866,0.324281,0.445931,0.422359,0.072402,18
17,0.002332,4.722705e-04,0.001998,6.257699e-07,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.632988,0.576771,0.557786,0.589182,0.031931,16

In [16]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:45
BMI:35
Children:4
Sex Male 0 or 1:1
Smoker Yes 0 or 1:1

In [17]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[15555.18875]